theme: ./src

siteConfig:
  title: Phạm Tiếp AdSense
  url: https://kadao.me
  author: Phạm Xuân Tiếp
  email: tiep@kadao.me
  phone: +84 0702227255
  description: Đây là trang giới thiệu sản phẩm tài khoản adsense của phạm xuân tiếp thái bình
  keywords: adsense acc, tài khoản gg adsense, mua bán adsense
  social:
    twitter: kadaome
    github: kadaome

themeConfig:
  nav:
    - text: projects
      link: /projects
    - text: writing
      link: /writing
    - text: newsletter
      link: /the-littoral-line
    - text: about
      link: /about
  social:
    rss: true
  lang: en

permalinks:
  post: /blog/:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  - resolve: saber-plugin-critical
  - resolve: saber-plugin-google-analytics
    options:
      trackId: "UA-116668558-1"
  - resolve: saber-plugin-sitemap
  # - resolve: saber-plugin-netlify-redirect

markdown:
  plugins:
    - resolve: markdown-it-attrs
    - resolve: markdown-it-sup
