theme: ./src

siteConfig:
  title: KdO Advertising and Adsense
  url: https://kadao.me
  author: Phạm Xuân Tiếp
  email: tiep@kadao.me
  phone: +84 0337036819
  description: tiếp bán tài khoản google adsense, gg adsense và viết lưu bút lưu trữ lại về hành trình làm việc và sinh sống học hỏi của bản thân
  keywords: adsense acc, tài khoản gg adsense, mua bán adsense
  social:
    twitter: kadao
    github: kadao

themeConfig:
  nav:
    - text: projects
      link: /projects
    - text: writing
      link: /writing
    - text: newsletter
      link: /the-littoral-line
    - text: about
      link: /about
  social:
    rss: true
  lang: en

permalinks:
  post: /blog/:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  - resolve: saber-plugin-critical
  - resolve: saber-plugin-google-analytics
    options:
      trackId: "UA-AAAAAAAAAB-1"
  - resolve: saber-plugin-sitemap
  # - resolve: saber-plugin-netlify-redirect

markdown:
  plugins:
    - resolve: markdown-it-attrs
    - resolve: markdown-it-sup
